### ISSUE TITLE
How to get hands on .dd file?

### ISSUE THREAD

**Issue by vaaino** [ossiozac/Raspberry-Pi-Zero-Rubber-Ducky-Duckberry-Pi#1]

**Comment by ossiozac** [comment]
This site https://github.com/hak5darren/USB-Rubber-Ducky/wiki/Payloads contains code which can be copied and pasted into a text file then change the .txt to .dd

This website https://ducktoolkit.com/ make the payload and download as inject.txt and change the extension and file name 

A .dd is just a text file with the extension changed. 

Hope this helps,
Zac.

**Comment by vaaino** [comment]
Thanks a lot, can finally continue my project!

Väinö

**Comment by ossiozac** [comment]
Glad it's working! I'll close the issue
