### ISSUE TITLE
Only see multi-color boot screen

### ISSUE THREAD

**Issue by meeseseang** [ossiozac/Raspberry-Pi-Zero-Rubber-Ducky-Duckberry-Pi#2]
After I installed the software, I altered the payload.dd file to say GUI SPACE instead of r because I have a mac. After I rebooted with it plugged into my mac I got nothing. So I plugged in the HDMI cable and used the same USB cable into my mac. All that happened was I saw the multi-colored boot screen for several minutes after plugging it in. Is there a way to fix this? Thank you in advance.

**Comment by ossiozac** [comment]
Hello,

Changing to GUI + Space makes sense to open the Spotlight yes.

It sounds like the system isn't booting into Rasbian at all.

Did you use the [ISO](http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2016-02-29/) listed in the ReadMe?

**Comment by meeseseang** [comment]
So I used the ISO you linked in and when it booted I changed the locales, wifi country, keyboard layout, and enabled ssh. I then tried to enable wifi on my Pi Zero W but there was no option in sudo raspi-config. I then edited the wpa_supplicant.conf file myself and added in the network. When I type ifconfig it only shows the interface lo and wlan0 is not included. Should I update the Raspi Zero to enable wifi?

**Comment by ossiozac** [comment]
I haven't tried this on a Pi Zero W - in theory you don't need WIFI for this to work.

When I was setting up the PI I used a USB to USB micro adaptor to a USB hub (for keyboard) then an ethernet to USB adaptor.

Due to the kernal in the listed ISO being required, I don't think there is a WIFI work around.

**Comment by billym357** [comment]
Will you ever update this so it'll work with the current kernal? I'd really like to use wifi.
