### ISSUE TITLE
Nothing happens when plugged into target

### ISSUE THREAD

**Issue by TUTOUNITYFR** [ossiozac/Raspberry-Pi-Zero-Rubber-Ducky-Duckberry-Pi#6]
I followed the tutorial, everything seems to work until step 7. When the Pi is plugged into the target (via USB port not power) nothing happens. I tried to unplugg and replugg multiple time for drivers but nothing happens. The green LED is lighting up.

I'm using the ISO provided (Rasbian Lite 2016-02-29).
Everything works from step 1 to 5, no errors.

I also tried to replace the default payload by the [Hello World payload](https://github.com/hak5darren/USB-Rubber-Ducky/wiki/Payload---hello-world) but no success. 

I'm using a Pi Zero W

Any idea ?

**Comment by lucki1000** [comment]
> 
> 
> I followed the tutorial, everything seems to work until step 7. When the Pi is plugged into the target (via USB port not power) nothing happens. I tried to unplugg and replugg multiple time for drivers but nothing happens. The green LED is lighting up.
> 
> I'm using the ISO provided (Rasbian Lite 2016-02-29).
> Everything works from step 1 to 5, no errors.
> 
> I also tried to replace the default payload by the [Hello World payload](https://github.com/hak5darren/USB-Rubber-Ducky/wiki/Payload---hello-world) but no success.
> 
> I'm using a Pi Zero W
> 
> Any idea ?

If the problem is actually for you, you can look in your lsusb to show if it is detected by your computer, or post the output here.

**Comment by TUTOUNITYFR** [comment]
I've ended up using the Rubber Ducky part of P4wnP1.
