### ISSUE TITLE
Raspberry Pi Zero W Not Installing correct image

### ISSUE THREAD

**Issue by unkrich** [ossiozac/Raspberry-Pi-Zero-Rubber-Ducky-Duckberry-Pi#7]
Looks like the image required in the readme is not working/compatible with my raspberry pi zero w v1.1 for some reason. After flashing the device, it won't turn on. Has anyone else experienced this issue/have a fix?

**Comment by shivasaxena** [comment]
Hi,
Can anyone provide an update on this? Is there a compatible version for Pi Zero W ?

**Comment by unkrich** [comment]
Hi @shivasaxena - we could not get it working with the Pi Zero W. If I remember correctly, I think the issue was that the version of Raspbian Lite necessary to use this project would not work with our Pi Zero W. When we tried other versions, the project wouldn't work. Good luck - closing as this seems to be an issue with the Pi/Raspbian and we did not use this project repository. Thanks!
